---
- name: Include OS and distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true

- name: Install nethermind
  include_tasks: "install.yml"

- name: Run OS specific installation tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}/install.yml"
        - "{{ ansible_os_family|lower }}/install.yml"
      skip: true

- name: Get IP address to bind to if not provided
  include_tasks: "network.yml"
  when: nethermind_host_ip is not defined

- name: Create config
  include_tasks: "config.yml"

- name: Create nethermind service
  include_tasks: "service.yml"
